<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>site.electrostatic</groupId>
        <artifactId>electrostatic-parent</artifactId>
        <version>0.0.4-SNAPSHOT</version>
    </parent>

    <artifactId>electrostatic-run</artifactId>
    <name>Electrostatic Website Builder</name>
    <description>Builds the Electrostatic web site for publishing on Github pages</description>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>site.electrostatic</groupId>
                <artifactId>electrostatic-maven-plugin</artifactId>
                <version>0.0.4-SNAPSHOT</version>
            </plugin>
        </plugins>
    </build>

</project>