package site.electrostatic.theme;

import site.electrostatic.content.book.BookPlugin;
import site.electrostatic.content.feed.FeedSubscriptionPlugin;
import site.electrostatic.content.podcast.PodcastPlugin;
import site.electrostatic.content.post.DraftPostPlugin;
import site.electrostatic.content.post.PostPlugin;
import site.electrostatic.content.staticfiles.ClasspathFilesPlugin;
import site.electrostatic.content.staticfiles.StaticFilesPlugin;
import site.electrostatic.engine.ContentModel;
import site.electrostatic.engine.Layout;
import site.electrostatic.feed.FeedPlugin;
import site.electrostatic.github.GithubActivityPlugin;
import site.electrostatic.index.IndexPlugin;
import site.electrostatic.plugins.ContentRenderPlugin;
import site.electrostatic.plugins.ContentTypePlugin;
import site.electrostatic.plugins.InitializationPlugin;
import site.electrostatic.plugins.Plugins;
import site.electrostatic.plugins.ThemePlugin;
import site.electrostatic.site.Site;
import site.electrostatic.tags.TagPlugin;
import site.electrostatic.theme.layouts.*;
import site.electrostatic.theme.pages.*;

import java.nio.file.Path;
import java.nio.file.Files;
import java.util.List;
import java.util.Map;

public class DefaultThemePlugin implements ContentTypePlugin, ContentRenderPlugin, ThemePlugin, InitializationPlugin {
  public static DefaultThemePlugin create() {
    return new DefaultThemePlugin();
  }

  @Override
  public void loadContent(Path sourceDirectory, Site site, ContentModel contentModel) {
    contentModel.addPage(_404Page.create());
    contentModel.addPage(TagsPage.create());
    contentModel.addPage(PodcastsPage.create());
    contentModel.addPage(BooksPage.create());
    contentModel.addPage(FeedsPage.create());
    contentModel.addPage(PostsPage.create("/posts/index.html", new site.electrostatic.engine.Pageable(1, 10)));
  }

  @Override
  public void loadLayout(Map<String, Layout> layouts) {
    layouts.put("default", DefaultLayout.create());
    layouts.put("home", HomeLayout.create());
    layouts.put("page", PageLayout.create());
    layouts.put("tag", TagLayout.create());
    layouts.put("book", BookLayout.create());
    layouts.put("podcast", PodcastLayout.create());
    layouts.put("post", PostLayout.create());
    layouts.put("posts", PostsLayout.create());
  }

  @Override
  public void registerPlugins() {

    Plugins.initializationPlugins.add(this);
    Plugins.contentTypePlugins.add(this);
    Plugins.contentRenderPlugins.add(this);

    BookPlugin.create().registerPlugins();
    PodcastPlugin.create().registerPlugins();
    PostPlugin.create().registerPlugins();
    FeedSubscriptionPlugin.create().registerPlugins();
    StaticFilesPlugin.create("_static").registerPlugins();
    GithubActivityPlugin.create().registerPlugins();

    FeedPlugin.create().registerPlugins();
    DraftPostPlugin.create().registerPlugins();
    TagPlugin.create().registerPlugins();
    IndexPlugin.create().registerPlugins();
    site.electrostatic.posts.PostsPlugin.create().registerPlugins();

    // TODO: jsass for sass compiling or move to ph-css or alternative
    ClasspathFilesPlugin.create(List.of(
            "theme/default/css/main.css",
            "theme/default/css/style.css",
            "theme/default/images/minima-social-icons.svg"
        ))
        .registerPlugins();

  }

  @Override
  public void initialize(Path sourceDirectory) {
    try {
      Files.createDirectories(sourceDirectory.resolve("_posts"));

      Path siteConfig = sourceDirectory.resolve("site-config.xml");
      if (Files.notExists(siteConfig)) {
        Files.writeString(siteConfig, """
            <site>
              <title>My Electrostatic Site</title>
              <baseUrl>http://localhost:8080</baseUrl>
              <theme>default</theme>
              <author>
                <name>Your Name</name>
              </author>
            </site>
            """);
      }

      Path samplePost = sourceDirectory.resolve("_posts/2026-01-01-hello-world.md");
      if (Files.notExists(samplePost)) {
        Files.writeString(samplePost, """
            ---
            title: Hello world
            date: 2026-01-01
            description: First post generated by electrostatic init.
            ---
            
            Welcome to your new Electrostatic site.
            """);
      }
    } catch (Exception e) {
      throw new RuntimeException("Failed to initialize default theme content", e);
    }
  }

}
